import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createSiteServer } from './serve.mjs';

await mkdir('artifacts',{recursive:true});
const server=createSiteServer('dist');await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const port=server.address().port;
const executablePath=process.env.CHROME_PATH??(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'/usr/bin/google-chrome');
let browser;
try{
  browser=await chromium.launch({executablePath,headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
  const page=await browser.newPage({viewport:{width:1440,height:960},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
  await page.goto(`http://127.0.0.1:${port}/?test=1&paused&time=6`);await page.waitForFunction(()=>window.__lost?.frames>2);
  assert.equal(await page.evaluate(()=>window.__lost.renderer),'WebGL');
  assert.equal(await page.locator('#controls').isVisible(),false);
  assert.equal(await page.locator('#sound').isVisible(),false);
  assert.equal(await page.locator('#play').isVisible(),true);
  assert.equal(await page.locator('#show-controls').count(),0);
  const opening=await page.evaluate(()=>({time:window.__lost.rat.current.time,frames:window.__lost.frames}));
  await page.waitForFunction(n=>window.__lost.frames>n+5,opening.frames);
  assert.equal(await page.evaluate(()=>window.__lost.rat.current.time),opening.time);
  assert.equal(await page.evaluate(()=>window.__lost.audio.state),'unopened');
  assert.equal(await page.evaluate(()=>performance.getEntriesByType('resource').some(r=>/\.(wav|m4a)$/.test(r.name))),false);
  await page.screenshot({path:'artifacts/browser-audio-muted.png'});
  await page.getByRole('button',{name:'Play with sound'}).click();
  await page.waitForFunction(()=>window.__lost.started&&window.__lost.audio.state==='running');
  assert.equal(await page.evaluate(()=>window.__lost.audio.muted),false);
  assert.ok(await page.evaluate(()=>window.__lost.audio.music.duration)>170);
  assert.ok(await page.evaluate(()=>window.__lost.audio.music.decodedBytes)<48*1024*1024);
  assert.equal(await page.locator('#play').isVisible(),false);
  assert.equal(await page.locator('#sound').isVisible(),true);
  await page.keyboard.press('Space');
  await page.waitForFunction(()=>window.__lost.audio.state==='suspended');
  const musicPaused=await page.evaluate(()=>({position:window.__lost.audio.music.position,frame:window.__lost.frames}));
  await page.waitForFunction(n=>window.__lost.frames>n+5,musicPaused.frame);
  assert.equal(await page.evaluate(()=>window.__lost.audio.music.position),musicPaused.position);

  await page.screenshot({path:'artifacts/browser-webgl.png'});
  assert.equal(await page.locator('#zoom').inputValue(),'90');
  assert.equal(await page.evaluate(()=>window.__lost.frame().patches.length),2);
  await page.keyboard.press('h');
  await page.getByRole('button',{name:'Face northwest',exact:true}).click();
  assert.equal(await page.evaluate(()=>window.__lost.rat.explore),true);
  await page.evaluate(()=>window.__lost.advance(2));
  assert.ok(Math.abs(await page.evaluate(()=>window.__lost.rat.exploration.route)-Math.atan2(-.5,-1.5))<1e-8);
  await page.goto(`http://127.0.0.1:${port}/?test=1&paused&time=12.5`);
  await page.waitForFunction(()=>window.__lost?.frames>2);
  assert.equal(await page.evaluate(()=>window.__lost.rat.exploration.phase),'investigate');
  await page.screenshot({path:'artifacts/browser-scent.png'});
  await page.evaluate(()=>window.__lost.advance(7));
  assert.equal(await page.evaluate(()=>window.__lost.rat.exploration.phase),'travel');

  await page.keyboard.press('h');
  await page.getByRole('button',{name:'Motion lab',exact:true}).click();
  assert.equal(await page.locator('#lab').isVisible(),true);
  await page.locator('#time-scale').selectOption('0.25');
  await page.getByRole('button',{name:'Walk 1',exact:true}).click();
  await page.evaluate(()=>window.__lost.advance(1));
  const beforeStep=await page.evaluate(()=>window.__lost.rat.current.time);
  await page.getByRole('button',{name:'Step 1/60 s',exact:true}).click();
  assert.ok(Math.abs(await page.evaluate(()=>window.__lost.rat.current.time)-beforeStep-1/60)<1e-8);
  await page.screenshot({path:'artifacts/browser-motion-lab.png'});
  await page.locator('#time-scale').selectOption('1');
  await page.getByRole('button',{name:'Motion lab',exact:true}).click();
  await page.getByRole('button',{name:'Sniff 3',exact:true}).click();assert.equal(await page.evaluate(()=>window.__lost.rat.requested),'sniff');
  await page.getByRole('button',{name:'Groom 5',exact:true}).click();assert.equal(await page.evaluate(()=>window.__lost.rat.requested),'groom');
  await page.getByRole('button',{name:'Face northwest',exact:true}).click();
  await page.evaluate(()=>window.__lost.advance(2));assert.equal(await page.evaluate(()=>window.__lost.rat.current.action),'groom');
  await page.locator('#mood').fill('100');await page.evaluate(()=>window.__lost.advance(4));assert.ok(await page.evaluate(()=>window.__lost.rat.current.mood)>.98);
  await page.screenshot({path:'artifacts/browser-home.png'});
  await page.getByRole('button',{name:'Play with sound'}).click();
  await page.waitForFunction(()=>window.__lost.started&&window.__lost.audio.state==='running');
  await page.locator('h1').click({force:true});await page.keyboard.press('3');assert.equal(await page.evaluate(()=>window.__lost.rat.requested),'sniff');
  await page.keyboard.press('h');assert.equal(await page.locator('#controls').isVisible(),false);await page.keyboard.press('h');
  await page.getByRole('button',{name:'Open field notes'}).click();assert.equal(await page.locator('dialog').isVisible(),true);await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Reset',exact:false}).click();
  await page.keyboard.down('ArrowRight');await page.waitForFunction(()=>window.__lost.rat.current.speed>.3);await page.keyboard.up('ArrowRight');assert.equal(await page.evaluate(()=>window.__lost.rat.requested),'idle');
  await page.waitForFunction(()=>!window.__lost.audio.loading&&window.__lost.audio.voices>0);
  assert.ok(await page.evaluate(()=>window.__lost.audio.voices)<=40);
  await page.keyboard.press('m');await page.waitForFunction(()=>window.__lost.audio.state==='suspended');
  assert.equal(await page.evaluate(()=>window.__lost.audio.muted),true);
  await page.keyboard.press('m');await page.waitForFunction(()=>window.__lost.audio.state==='running');
  await page.locator('#pause').click();await page.waitForFunction(()=>window.__lost.audio.state==='suspended');
  assert.equal(await page.evaluate(()=>window.__lost.audio.muted),false);
  await page.locator('#pause').click();await page.waitForFunction(()=>window.__lost.audio.state==='running');
  await page.locator('.sound-mix summary').click();
  await page.locator('[data-sound="rain"]').fill('0');
  await page.locator('#volume-music').fill('0');
  await page.waitForFunction(()=>window.__lost.audio.gains.music<.0001);
  assert.ok(await page.evaluate(()=>window.__lost.audio.gains.rat)>.5);
  assert.equal(await page.locator('#level-music').textContent(),'0%');
  await page.locator('#volume-master').fill('0');
  await page.waitForFunction(()=>window.__lost.audio.masterGain<.0001);
  await page.locator('#reset-mix').click();
  await page.waitForFunction(()=>window.__lost.audio.gains.music>.27&&window.__lost.audio.masterGain>.84);
  await page.screenshot({path:'artifacts/browser-audio-panel.png'});
  await page.locator('.sound-mix summary').click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/browser-mobile.png'});
  assert.ok(await page.locator('#sound').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
  assert.equal(await page.locator('#zoom').inputValue(),'90');
  const actorBottom=await page.evaluate(()=>{
    const frame=window.__lost.frame(),body=frame.commands.find(c=>c.id.startsWith('rat-body'));
    return (body.y+body.height)/frame.height*innerHeight;
  });
  assert.ok(actorBottom<await page.locator('#controls').evaluate(el=>el.getBoundingClientRect().top));
  assert.ok(await page.locator('#controls').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.goto(`http://127.0.0.1:${port}/?test=1&renderer=canvas&paused&time=6`);await page.waitForFunction(()=>window.__lost?.frames>2);
  assert.equal(await page.evaluate(()=>window.__lost.renderer),'Canvas 2D');await page.screenshot({path:'artifacts/browser-canvas-mobile.png'});
  await page.setViewportSize({width:1440,height:960});
  await page.waitForFunction(()=>document.querySelector('#scene').width===Math.round(innerWidth/Math.max(1.25,innerWidth/1100)));
  const resizedFrame=await page.evaluate(()=>window.__lost.frames);
  await page.waitForFunction(n=>window.__lost.frames>n+2,resizedFrame);
  await page.screenshot({path:'artifacts/browser-canvas.png'});
  // Failed loading remains recoverable and does not break the visual scene.
  await page.route('**/*.wav',route=>route.fulfill({status:200,contentType:'audio/wav',body:'Invalid audio for retry test'}));
  await page.locator('#play').click();await page.waitForFunction(()=>window.__lost.started&&!!window.__lost.audio.error);
  assert.equal(await page.evaluate(()=>window.__lost.audio.muted),true);
  assert.equal(await page.locator('#sound').isEnabled(),true);
  await page.unroute('**/*.wav');
  await page.locator('#sound').click();await page.waitForFunction(()=>!window.__lost.audio.loading&&!window.__lost.audio.muted);
  const mobile=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
  const touch=await mobile.newPage();touch.on('pageerror',error=>errors.push(error.message));
  await touch.goto(`http://127.0.0.1:${port}/?test=1`);await touch.waitForFunction(()=>window.__lost?.frames>2);
  await touch.locator('#play').tap();await touch.waitForFunction(()=>window.__lost.started);
  for(let i=0;i<4;i++)await touch.touchscreen.tap(80,360);
  assert.equal(await touch.locator('#controls').isVisible(),false);
  await touch.touchscreen.tap(80,360);
  assert.equal(await touch.locator('#controls').isVisible(),true);
  assert.equal(await touch.evaluate(()=>window.__lost.rat.explore),true);
  await touch.screenshot({path:'artifacts/browser-five-taps.png'});
  await touch.locator('.sound-mix summary').click();
  await touch.locator('#volume-music').fill('45');
  assert.equal(await touch.locator('#level-music').textContent(),'45%');
  assert.ok(await touch.locator('.audio-panel').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));
  await touch.locator('.audio-panel').scrollIntoViewIfNeeded();
  await touch.screenshot({path:'artifacts/browser-audio-mobile.png'});
  await touch.locator('.sound-mix summary').click();
  for(let i=0;i<5;i++)await touch.touchscreen.tap(80,250);
  assert.equal(await touch.locator('#controls').isVisible(),false);
  await touch.screenshot({path:'artifacts/browser-mobile-playing.png'});
  await mobile.close();
  assert.deepEqual(errors,[]);console.log('Browser checks passed: WebGL, Canvas, desktop/mobile, actions, facing, mood, keyboard, pause, notes, exploration routes, scent returns, responsive framing, shadow patches, Play-gated startup, five-tap controls, lazy audio, pause/resume, mix controls and retry.');
}finally{await browser?.close();server.close();}
